[[parameter]]
    model       = "Shifter"
    market      = "BTCUSD@deribit"
    BuyVolume   = 100
    SellVolume  = 100
    MaxDelta    = 1000

[[parameter]]
    model       = "Mixer"
    target      = "BTCUSD@deribit"
    market      = "BTCUSD@deribit"
    Weight      = 1.0

[[market]]
    market      = "BTCUSD@deribit"
    symbol      = "BTC-PERPETUAL"
    exchange    = "deribit"

[[account]]
    account     = "REN_DERIBIT_UAT"

[[position]]
    market      = "BTCUSD@deribit"
    portfolio   = "MM1"
    position    = 0.

[app]
    app         = "mmaker"
    model       = "CryptoMixerUnstable"
