################ M A R K E T S #################
[[market]]
    #label           = "~FUT ~Q1 ~BIT" # set of labels (groups) for the symbol
    symbol          = ["BTC-PERPETUAL","BTC-29MAR24"]
    exchange        = "deribit"
#    tick_size       = 0.01
    mdata_gateway   = "deribit"
    trade_gateway   = "deribit"
#    account         = "REN_DERIBIT"

[oms]
    position_source     = "PORTFOLIO" # "ORDERS"

# specify trade gateway for each [exchange,account] pair
[[account]]
    exchange        = "deribit"
    account         = "REN_DERIBIT"
    trade_gateway   = "deribit"

# attach portfolio to accounts
[[parameter]]
    label = "portfolio"
    account = "REN_DERIBIT"
    exchange = "deribit"
    value = "LG1"     # specify portfolio LG1 for exchange account REN_DERIBIT
    symbol = ""

[[parameter]]
    label = "enabled"
    account = "LG1"   # this is portfolio (not account) to liquidate
    exchange = "lqs"    # FIXME: this is the name of the pricer
    value = "true"      # enabled means should liquidate

# underlying symbol for each contract (setup is going per liquidation portfolio)
[[parameter]]
    label           = "underlying"
    exchange        = "deribit"
    symbol          = ["BTC-PERPETUAL",             "BTC-29MAR24"]
    value           = ["lqs:BTC/USD",               "lqs:BTC/USD"]  # exchange:symbol
    account         = ["LG1"]

# delta greek
[[parameter]]
    label           = "delta_greek"
    exchange        = "deribit"
    symbol          = ["BTC-PERPETUAL",             "BTC-29MAR24"]
    value           = ["1",                         "1"]
    account         = ["LG1"]

# min delta (in USD) for the whole combination
[[parameter]]
    label           = "delta_min"
    exchange        = "lqs"
    symbol          = "BTC/USD"
    value           = "-1000"
    account         = "LG1"         # portfolio (or strategy id?)

# max delta (in USD) for the whole combination
[[parameter]]
    label           = "delta_max"
    symbol          = "BTC/USD"
    exchange        = "lqs"
    value           = "1000"
    account         = "LG1"   

# multiplier contract volume -> delta in USD
[[parameter]]
    label           = "delta_by_volume"
    exchange        = "deribit"
    symbol          = ["BTC-PERPETUAL",         "BTC-29MAR24"]
    value           = ["1",                     "1"]
    account         = ["LG1"]

# specify subaccount to trade legs through
[[parameter]]
    label           = "account"
    exchange        = "deribit"
    symbol          = ["BTC-PERPETUAL",         "BTC-29MAR24"]
    value           = ["REN_DERIBIT",           "REN_DERIBIT"]
    account         = ["LG1"]

[[parameter]]
    label           = "buy_volume"
    exchange        = "deribit"
    symbol          = ["BTC-PERPETUAL",         "BTC-29MAR24"]
    value           = ["100",                   "100"]
    account         = ["LG1"]

[[parameter]]
    label           = "sell_volume"
    exchange        = "deribit"    
    symbol          = ["BTC-PERPETUAL",         "BTC-29MAR24"]
    value           = ["100",                   "100"]
    account         = ["LG1"]

# ban future order placements after order has been fully filled (separately each side of the book)
[[parameter]]
    label           = "post_fill_timeout"
    symbol          = ["BTC-PERPETUAL",         "BTC-29MAR24"]
    exchange        = "deribit"
    value           = ["100",                  "100"]
    account         = ["LG1"]
