################ M A R K E T S #################
[[market]]
    #label           = "~FUT ~Q1 ~BIT" # set of labels (groups) for the symbol
    symbol          = ["BTC-PERPETUAL","BTC-29MAR24"]
    exchange        = "deribit"
#    tick_size       = 0.01
    mdata_gateway   = "deribit"
    trade_gateway   = "deribit"

[oms]
    position_source     = "PORTFOLIO" # "ORDERS"

# attach portfolio to accounts
[[parameter]]
    label = "portfolio"
    account = "A1"
    exchange = "deribit"
    value = "P:100"     # this is portfolio name
    symbol = ""

[[parameter]]
    label = "enabled"
    account = "P:100"   # this is portfolio (not account) to liquidate
    exchange = "lqs"    # FIXME: this is the name of the pricer
    value = "true"      # flag to liquidate

# underlying symbol for each contract
[[parameter]]
    label           = "underlying"
    exchange        = "deribit"
    symbol          = ["BTC-PERPETUAL",             "BTC-29MAR24"]
    value           = ["lqs:BTC/USD",               "lqs:BTC/USD"]  # exchange:symbol

# delta greek
[[parameter]]
    label           = "delta_greek"
    exchange        = "deribit"
    symbol          = ["BTC-PERPETUAL",             "BTC-29MAR24"]
    value           = ["1",                         "1"]

# min delta (in USD) for the whole combination
[[parameter]]
    label           = "delta_min"
    exchange        = "lqs"
    symbol          = "BTC/USD"
    value           = "-1000"

# max delta (in USD) for the whole combination
[[parameter]]
    label           = "delta_max"
    symbol          = "BTC/USD"
    exchange        = "lqs"
    value           = "1000"

# multiplier contract volume -> delta in USD
[[parameter]]
    label           = "delta_by_volume"
    exchange        = "deribit"
    symbol          = ["BTC-PERPETUAL",         "BTC-29MAR24"]
    value           = ["1",                     "1"]

[[parameter]]
    label           = "account"
    exchange        = "deribit"
    symbol          = ["BTC-PERPETUAL",         "BTC-29MAR24"]
    value           = ["A1",                    "A1"]


[[parameter]]
    label           = "buy_volume"
    exchange        = "deribit"
    symbol          = ["BTC-PERPETUAL",         "BTC-29MAR24"]
    value           = ["100",                   "100"]

[[parameter]]
    label           = "sell_volume"
    exchange        = "deribit"    
    symbol          = ["BTC-PERPETUAL",         "BTC-29MAR24"]
    value           = ["100",                   "100"]

# ban future order placements after order has been fully filled (separately each side of the book)
[[parameter]]
    label           = "post_fill_timeout"
    symbol          = ["BTC-PERPETUAL",         "BTC-29MAR24"]
    exchange        = "deribit"
    value           = ["100",                  "100"]
