################ M A R K E T S #################
[[market]]
    label           = "~FUT ~Q1 ~BIT" # set of labels (groups) for the symbol
    symbol          = "BTC-27OCT23"
    exchange        = "deribit"
    tick_size       = 0.01
    mdata_gateway   = "deribit"
    trade_gateway   = "deribit"

[[market]]
    label           = "~PERP"
    symbol          = "BTC-PERPETUAL"
    exchange        = "deribit"
    tick_size       = 0.01
    mdata_gateway   = "deribit"
    trade_gateway   = "deribit"

[[portfolio]]
    name            = "L"            # liquidation strategy portfolio 
    strategy_id     = 100

[[portfolio]]                          # account's portfolio
    name            = "D1"
    account         = "A1"
    exchange        = "deribit"

[[portfolio]]
    name            = "D2"
    account         = "A2"
    exchange        = "deribit"

# define pricing nodes....

[[parameter]]
    label           = "top_of_book"
    symbol          = "D:BTC.P:p"
    exchange        = "pricer"                              # used to route the parameter into pricer for now
    value           = "deribit:BTC-PERPETUAL"

[[parameter]]
    label           = "multiplier"
    symbol          = "D:BTC.P:p"
    exchange        = "pricer"
    value           = "1"

# define exposure nodes...

[[parameter]]
    label           = "exposure"                            # push exposure into nodes
    exchange        = "pricer"
    symbol          = ["D:BTC.P:e:D1,                       "D:BTC.P:e:D2",             "D:BTC.P:e:L"]    # exposure (positions) nodes
    account         = ["D1",                                "D2"                        "L"]              # portfolio
    value           = ["100",                                "-100",                    "20"]             # sets exposure manually

# define quoting nodes...
[[parameter]]
    label           = "ref:price"
    exchange        = "pricer"
    symbol          = ["D:BTC.P:q:D1",                      "D:BTC.P:q:D2"]             # references from quoting nodes q:D1, q:D2
    value           = ["D:BTC.P:p,                          "D:BTC.P:p"]                # ... to pricing node p

[[parameter]]
    label           = "ref:exposure"                        # reference from quote nodes to exposure nodes
    exchange        = "pricer"
    symbol          = "D:BTC.P:q:D1"                        # quote node
    value           = ["D:BTC.P:e:D1",                      "D:BTC.P:e:D2",             "D:BTC.P:e:L"]     # references from q:D1 to e:D1, e:D2, e:L nodes

[[parameter]]
    label           = "ref:exposure"                        # reference from quote nodes to exposure nodes
    exchange        = "pricer"
    symbol          = "D:BTC.P:q:D2"                        # quote node
    value           = ["D:BTC.P:e:D1",                      "D:BTC.P:e:D2",             "D:BTC.P:e:L"]     # references from q:D2 to e:D1, e:D2, e:L nodes

# define execution for quoting nodes...
[[parameter]]
    label           = "execution"                           # connect quote nodes to oms
    exchange        = "pricer"
    symbol          = ["D:BTC.P:q:D1",                      "D:BTC.P:q:D2"]             # quoting nodes
    value           = "deribit:BTC-PERPETUAL"                                           # real target instruments
    account         = ["D1",                                "D2"]                       # portfolios

# define pipeline for quoting nodes...
[[parameter]]
    label           = "pipeline"                            # set pipeline (list of computing algorithms) 
    exchange        = "pricer"
    symbol          = ["D:BTC.P:q:D1",                      "D:BTC.P:q:D2"]             # quoting nodes
    value           = "quote_shift quote_spread"
    account         = ["D1",                                "D2"]                       # portfolios

[[parameter]]
    label           = "quote_spread:min_spread"            # spread constraint
    exchange        = "pricer"    
    symbol          = ["D:BTC.P:q:D1",                      "D:BTC.P:q:D2"]             # quoting nodes
    value           = "10 BP"                                                           # spread to maintain

[[parameter]]
    label           = "quote_spread:max_spread"            # spread constraint
    exchange        = "pricer"    
    symbol          = ["D:BTC.P:q:D1",                      "D:BTC.P:q:D2"]             # quoting nodes
    value           = "10 BP"                                                           # spread to maintain

[[parameter]]
    label           = "quote_spread:max_spread"            # spread constraint
    exchange        = "pricer"    
    symbol          = ["D:BTC.P:q:D1",                      "D:BTC.P:q:D2"]             # quoting nodes
    value           = "10 BP"                                                           # spread to maintain

[[parameter]]
    label           = "ema"                                                             # price smoothing
    exchange        = "pricer"    
    symbol          = ["D:BTC.P:q:D1",                       "D:BTC.P:q:D2"]            # quoting nodes
    value           = "0.001"

