################ M A R K E T S #################
[[market]]
    label           = "~FUT ~Q1 ~BIT" # set of labels (groups) for the symbol
    symbol          = "BTC-27OCT23"
    exchange        = "deribit"
    tick_size       = 0.01
    mdata_gateway   = "deribit"
    trade_gateway   = "deribit"

[[market]]
    label           = "~PERP"
    symbol          = "BTC-PERPETUAL"
    exchange        = "deribit"
    tick_size       = 0.01
    mdata_gateway   = "deribit"
    trade_gateway   = "deribit"

[[account]]
    account                 = "A1"
    exchange                = "deribit"

# set parameter multiplier=1 for 'mdata.deribit:BTC.P' node
[[parameter]]
    label           = "multiplier"
    symbol          = "BTC.P"
    exchange        = "mdata.deribit"
    value           = "1"

# set spread.target=10bp for 'mdata.deribit:BTC.P' node 
[[parameter]]
    label           = "spread.target"
    symbol          = "BTC.P"
    exchange        = "mdata.deribit"
    value           = "bp 10"

#  'mdata.deribit:BTC.P' node to consume 'deribit:BTC-PERPETUAL' market for market data
[[parameter]]
    label           = "mdata"
    symbol          = "BTC.P"
    exchange        = "mdata.deribit"
    value           = "deribit:BTC-PERPETUAL"

# set ref to src node 'mdata.deribit:BTC.P'  from dst node 'quote.deribit:BTC.P' with weight 0.5
[[parameter]]
label           = "ref.weight"
symbol          = "BTC.P"
exchange        = "quote.deribit"  # dst
value           = "mdata.deribit:BTC.P 0.5" # src

# list functions to apply to 'quote.deribit:BTC.P' node, in order
[[parameter]]
label           = "func"
symbol          = "BTC.P"
exchange        = "quote.deribit"
value           = "product ema shift spread"

# set parameter ema.omega=1 for 'quote.deribit:BTC.P' node
[[parameter]]
label           = "ema.omega" # name of struct and name of field
symbol          = "BTC.P"
exchange        = "quote.deribit"
value           = "0.001"


# set execution for 'quote.deribit:BTC.P' node to 'deribit:BTC-PERPETUAL' instrument
[[parameter]]
label           = "exec"
symbol          = "BTC.P"
exchange        = "quote.deribit"
value           = "deribit:BTC-PERPETUAL"