# lqs service

# specify mdata and trade gateways for symbols, see market::Info
[[market]]
    symbol          = ["BTC-PERPETUAL", "BTC-29MAR24",  "BTC-1MAR24", "BTC_USDT"]
    exchange        = "deribit"
    mdata_gateway   = "deribit"

[oms]
    # core::PositionSource::PORTFOLIO takes position from roq::PositionUpdate
    # core::PositionSource::ORDERS takes initial snapshot from roq::PositionUpdate, and updates position using roq::OrderUpdate (when fills or partial fills are detected)
    position_source     = "PORTFOLIO" # "ORDERS"

#  map account to portfolio (all account trades are collected into portfolio automatically using PositionUpdate or PositionUpdate + Orders)
[[account]]
    exchange        = "deribit"
    account         = "REN_DERIBIT" # client1
    trade_gateway   = "deribit"
    portfolio       = "100"         # identifier of the portfolio, same as strategy_id for now
    portfolio_name  = "LG100"

[[account]]
    exchange        = "deribit"
    account         = "BRO_DERIBIT" # client2
    trade_gateway   = "deribit"
    portfolio       = "100"         # identifier of the portfolio, same as strategy_id for now
    portfolio_name  = "LG100"


# ban future order placements after order has been fully filled (separately each side of the book)
[[parameter]]
    strategy        = "100"
    label           = "oms:post_fill_timeout"
    symbol          = ["BTC-PERPETUAL",         "BTC-29MAR24" ]
    exchange        = "deribit"
    account         = "REN_DERIBIT"
    value           = ["2000",                  "4000"]

[[parameter]]
    strategy        = "100"
    label           = "oms:post_cancel_timeout"
    symbol          = ["BTC-PERPETUAL",         "BTC-29MAR24" ]
    exchange        = "deribit"
    account         = "REN_DERIBIT"
    value           = ["200",                  "200"]

[[parameter]]
    strategy        = "100"
    label           = "oms:ban_modify"
    symbol          = ["BTC-PERPETUAL",         "BTC-29MAR24" ]
    exchange        = "deribit"
    account         = "REN_DERIBIT"
    value           = "false"

[[parameter]]
    strategy        = "100"
    label           = "lqs:enabled"
    value           = "true"        # false = do not do any trading for this strategy

# underlying symbol for each contract.
[[parameter]]
    strategy        = "100"
    label           = "lqs:underlying"
    exchange        = "deribit"      
    account         = "REN_DERIBIT"  
    symbol          = ["BTC-PERPETUAL",             "BTC-29MAR24"]
    value           = ["deribit:BTC_USDT",          "deribit:BTC_USDT"]      # exchange:symbol

[[parameter]]
    strategy        = "100"
    label           = "lqs:contract_style"
    exchange        = "deribit"       
    account         = "REN_DERIBIT" 
    symbol          = ["BTC-PERPETUAL",             "BTC-29MAR24"]
    value           = ["INVERSE",                   "INVERSE"]      # LINEAR, INVERSE, SPOT


[[parameter]]
    strategy        = "100"
    label           = "lqs:execution_mode"
    exchange        = "deribit"        
    account         = "REN_DERIBIT"
    symbol          = ["BTC-PERPETUAL",             "BTC-29MAR24"]
    value           = "CROSS" # ["CROSS",                      "CROSS"]             # CROSS, JOIN, JOIN_PLUS, CROSS_MINUS


# delta greek (price sensitivity to the underlying price)
[[parameter]]
    strategy        = "100"
    label           = "lqs:delta_greek"
    exchange        = "deribit"
    account         = "REN_DERIBIT"
    symbol          = ["BTC-PERPETUAL",             "BTC-29MAR24"]
    value           = ["1",                         "1"]

# min delta (in USD) for the whole combination
[[parameter]]
    strategy        = "100"
    label           = "lqs:slippage"
    exchange        = "deribit"
    account         = "REN_DERIBIT"
    symbol          = ["BTC-PERPETUAL",             "BTC-29MAR24"]
    value           = ["100",                         "100"] # in B.P.

# min delta (in USD) for the whole combination
[[parameter]]
    strategy        = "100"
    label           = "lqs:underlying:delta_min"
    exchange        = "deribit"                             # here exchanges is namespace for symbols published by the lqs service
    symbol          = "BTC_USDT"
    account         = "REN_DERIBIT"
    value           = "-100"

# max delta (in USD) for the whole combination
[[parameter]]
    strategy        = "100"
    label           = "lqs:underlying:delta_max"
    exchange        = "deribit"    
    symbol          = "BTC_USDT"
    account         = "REN_DERIBIT"
    value           = "100"

# multiplier contract volume -> delta in USD
[[parameter]]
    strategy        = "100"
    label           = "lqs:delta_by_volume"
    exchange        = "deribit"
    account         = "REN_DERIBIT"
    symbol          = ["BTC-PERPETUAL",         "BTC-29MAR24"]
    value           = ["10",                     "10"]

[[parameter]]
    strategy        = "100"
    label           = "lqs:buy_volume"
    exchange        = "deribit"
    account         = "REN_DERIBIT"
    symbol          = ["BTC-PERPETUAL",         "BTC-29MAR24",      "BTC-1MAR24"]
    value           = ["10",                   "10",                "10"]

[[parameter]]
    strategy        = "100"
    label           = "lqs:sell_volume"
    exchange        = "deribit"    
    account         = "REN_DERIBIT"
    symbol          = ["BTC-PERPETUAL",         "BTC-29MAR24",      "BTC-1MAR"]
    value           = ["10",                   "10",                "10"]


### not-implemented yet
[[parameter]]
    strategy        = "100"
    label           = "lqs:price_threshold"
    exchange        = "deribit"
    account         = "REN_DERIBIT"
    symbol          = ["BTC-PERPETUAL",         "BTC-29MAR24"]
    value           = ["100",                   "100"]

### not-implemented yet
[[parameter]]
    strategy        = "100"
    label           = "lqs:price_units"
    exchange        = "deribit"
    account         = "REN_DERIBIT"
    symbol          = ["BTC-PERPETUAL",         "BTC-29MAR24"]
    value           = ["BP",                    "BP"]

