################ M A R K E T S #################
[[market]]
    label           = "~FUT ~Q1 ~BIT" # set of labels (groups) for the symbol
    symbol          = "BTC-27OCT23"
    exchange        = "deribit"
    tick_size       = 0.01
    mdata_gateway   = "deribit"
    trade_gateway   = "deribit"

[[market]]
    label           = "~PERP"
    symbol          = "BTC-PERPETUAL"
    exchange        = "deribit"
    tick_size       = 0.01
    mdata_gateway   = "deribit"
    trade_gateway   = "deribit"

# define liquidation group
[[portfolio]]                          
    name            = "D1"
    account         = "A1"
    exchange        = "deribit"

[[portfolio]]
    name            = "D2"
    account         = "A2"
    exchange        = "deribit"

# define parameters
[[parameter]]
    label           = "underlying"
    symbol          = "BTC-PERPETUAL"
    exchange        = "deribit"
    value           = "BTC/USD"

[[parameter]]
    label           = "underlying"
    symbol          = "BTC-SEP24"
    exchange        = "deribit"
    value           = "BTC/USD"

[[parameter]]
    label           = "delta"           # delta with respect to the underlying
    symbol          = "BTC-PERPETUAL"
    exchange        = "deribit"
    value           = "1"

[[parameter]]
    label           = "delta"
    symbol          = "BTC-SEP24"
    exchange        = "deribit"
    value           = "1"

[[parameter]]
    label           = "volume_multiplier"
    symbol          = "BTC-PERPETUAL"
    exchange        = "deribit"
    value           = "1"

[[parameter]]
    label           = "volume_multiplier"
    symbol          = "BTC-SEP24"
    exchange        = "deribit"
    value           = "1"

[[parameter]]
    label           = "buy_volume"
    symbol          = "BTC-PERPETUAL"
    exchange        = "deribit"
    value           = "100"

[[parameter]]
    label           = "sell_volume"
    symbol          = "BTC-PERPETUAL"
    exchange        = "deribit"
    value           = "100"

[[parameter]]
    label           = "buy_volume"
    symbol          = "BTC-SEP24"
    exchange        = "deribit"
    value           = "100"

[[parameter]]
    label           = "sell_volume"
    symbol          = "BTC-SEP24"
    exchange        = "deribit"
    value           = "100"
