// (c) copyright 2023 Mikhail Mitkevich
#pragma once

#include <magic_enum.hpp>

namespace roq {
namespace core {

// portfolio::Manager's ExposureUpdate is generated by...
enum class PositionSource {
    UNDEFINED,
    ORDERS, // use portfolio snapshot and update using OrderUpdate
    TRADES, // use portfolio snapshot and update using Trades
    PORTFOLIO, // use portfolio snapshot and update using PortfolioUpdate
};

} // core
} // roq

ROQ_CORE_FMT_DECL(roq::core::PositionSource, "{}", magic_enum::enum_name(_));